### PR TITLE
Readded the PDF version of Sammanfattning-Meris-Felix.tex

### PR DESCRIPTION
**Pull request by velixo**

### CODE REVIEW

**Comment by felixmulder** [comment]
Already done earlier today :)

**Comment by velixo** [comment]
Can't see the compiled PDF file there though? Until all .tex files are converted to Markdown, it would be nice to have the PDF files up (especially for LaTeX noobs like me :D )

**Comment by antoneliasson** [comment]
PDFs can be seen as binary releases of source code (tex and markdown). There are probably better solutions for hosting then than the main git repository (Bintray seems popular) but until someone sets that up for us, I think we should keep putting PDFs into this repo. They aren't taking up *that* much space.

**Comment by velixo** [comment]
Also I'd say that since this isn't really a code repository, I don't see the point in adhereing to the "source-code only" philosophy.

**Comment by AmusableLemur** [comment]
There are [releases](https://github.com/datateknik-lth/datateknik-lth/releases) available for hosting generated binary files on GitHub. Maybe an option?

**Comment by felixmulder** [comment]
Releases would be an option if someone wanted to make some form of build script for the repository. I for one am not.

The idea is to convert the LaTeX files to markdown. This is easy using pandoc:

```bash
$ pandoc -f latex -t markdown file.tex > out.md
```
Yes, the formulas will not be converted. This can be fixed using  the script I just commited in 58eb81c

Usage:

```bash
$ ./tex2img.py "$ x \cdot 5 = 10 $" out.png
```

**Comment by antoneliasson** [comment]
I don't think releases are suitable for this. If I understand them correctly they are basically snapshots of the repository (i.e. git tags). Since we don't "feature freeze" or make "stable releases" of our documentation there is little point in tagging the history.

Manually rendering math formulas to images is too much work. I think we should make them render during display time in the users' browsers instead, like in issue #28. Until then I say commit PDFs.

**Comment by velixo** [comment]
Aren't math equations declared in LaTeX using certain tags? If so, wouldn't it be simple for someone with good bash/python/scripting knowledge to take an entire .tex document as input, find the relevant equations and then export them as images? I don't see how it would be so much work in that case. 

It would just be a case of using the pandoc script to convert to markdown, generate images for the math formula pictures using the hypothetical script above, and then paste them into the right place in the markdown.

There aren't *that* many courses in this repo. Sure it's a bit of work, but I wouldn't mind joining in to do that process.

**Pull request merged**
