### PR TITLE
Elaborated on some answers, added examples and added some more answers

### PR DESCRIPTION
**Pull request by velixo**
Concerning Minne -> 2: Maybe I'm just nitpicking, but ["A random-access memory device allows data items to be read and written in *roughly* the same amount of time..."](http://en.wikipedia.org/wiki/Random-access_memory)

### CODE REVIEW

**Comment by AmusableLemur** [comment]
Not sure what the consensus is here, but wouldn't it be better if the images were stored in the repository?

**Comment by antoneliasson** [comment]
I agree. They could also be inlined in the document instead of linked: http://daringfireball.net/projects/markdown/syntax#img

**Comment by felixmulder** [comment]
Agreed, please include the image in your PR and squash your commits.

**Comment by velixo** [comment]
Agreed, felt a bit iffy posting these links. Will check out how to add files as a non-contributor

**Comment by velixo** [comment]
I fixed the links and added the images to a new folder and commited it, but this goshdarn squash thing isn't working correctly :P

**Pull request merged**
